# @package _global_
defaults:
  - override /paths: plgrid
  - override /model: musicgen-small-net-classifier
  - override /experiment: layer-gradient-x-activation-medium
  - override /trainer: small
  - override /logger: wandb

data:
  batch_size: 32
