# @package _global_
defaults:
  - override /paths: plgrid
  - override /model: musicgen-small
  - override /experiment: layer-feature-ablation-medium
  - override /logger: wandb

data:
  batch_size: 32
