_target_: "src.tta.config.ModelConfig"
model:
  _target_: "src.tcav.model.CustomMusicGen"
  processor:
    _target_: "transformers.AutoProcessor.from_pretrained"
    pretrained_model_name_or_path: "facebook/musicgen-small"
    device: ${device}
  model:
    _target_: "transformers.MusicgenForConditionalGeneration.from_pretrained"
    pretrained_model_name_or_path: "facebook/musicgen-small"
  max_new_tokens: 256
model_id: "musicgen-small"
