template: |
  <|begin_of_text|><|start_header_id|>system<|end_header_id|>{system_prompt}<|eot_id|>
  <|start_header_id|>user<|end_header_id|>{user_prompt}<|eot_id|>
  <|start_header_id|>assistant<|end_header_id|>{assistant_response}<|eot_id|><|end_of_text|>
eval_template: |
  <|begin_of_text|><|start_header_id|>system<|end_header_id|>{system_prompt}<|eot_id|>
  <|start_header_id|>user<|end_header_id|>{user_prompt}<|eot_id|>
  <|start_header_id|>assistant<|end_header_id|>
prompt_delimiter: |
  <|start_header_id|>assistant<|end_header_id|>
system_prompt: You are a music description expert that creates detailed, technical descriptions of songs based on their musical characteristics. Make sure to include references to specific musical elements such as instrumentation, rhythm, melody, harmony, dynamics, and production techniques.
user_prompt_template: "Write a detailed song description based on the following characteristics:{tags}. The description accurately encompass all characteristics. Don't write the title, artist name or album name. Respond with ONLY the song description - no special characters, emotes, or additional formatting:"