site_name: "ConceptCaps"

theme:
  name: "material"
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
    - navigation.expand
  palette: "dark"

nav:
  - Home: index.md
  - Getting Started:
    - Configuration: config.md
    - Data: data.md
    - Notebooks: notebooks.md
  - Code Reference:
    - Overview: code/reference.md
    - Caption: code/caption.md
    - VAE: code/vae.md
    - TCAV: code/tcav.md
    - TTA: code/tta.md
    - Utilities: code/utils.md

plugins:
  - search
  - section-index
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/pl/3.12/objects.inv
          paths: [src]
          options:
            show_bases: true
            show_source: false
            allow_inspection: true
            show_root_heading: true
            parameter_headings: true
            merge_init_into_class: true
            signature_crossrefs: true
            summary: true
            show_symbol_type_toc: true
            show_symbol_type_heading: true
            show_if_no_docstring: false
            members_order: source
            filters:
              - "!^__all__$"
              - "!^__version__$"
              - "!^__author__$"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: plot
          class: plot
          # format: !!python/name:matplotlib.pyplot.figure
