[tool.poetry]
name = "music-gen-interpretability"
version = "0.1.0"
description = ""
authors = ["Bruno Sienkiewicz <01178591@pw.edu.pl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.dev-dependencies]
mkdocs = "^1.5.3"
mkdocs-material = "^9.5.3"
mkdocs-section-index = "^0.3.8"
mkdocstrings = "^0.24.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
