[tool.poetry]
name = "music-gen-interpretability"
version = "0.1.0"
description = ""
authors = ["Bruno Sienkiewicz <01178591@pw.edu.pl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
