# @package _global_
defaults:
  - override /prompt: llama_short
  - override /model: caption/llama_3.1_8b_instruct
  - override /evaluation: caption/no_judge
  - override /lora: caption/low_rank
  - override /generation: caption/best
  - override /paths: plgrid
  - override /logger: wandb

data:
  batch_size: 96
  dataloader_num_workers: 16
  max_test_samples: null
  max_val_samples: null
  max_train_samples: null

model:
  checkpoint: ${oc.env:LORA_CHECKPOINT_PATH,/path/to/lora/checkpoint}
