# @package _global_
defaults:
  - override /prompt: llama
  - override /model: caption/llama_3.1_70b_instruct
  - override /trainer: caption_lightning/learn
  - override /lora: caption/regularization
  - override /evaluation: caption/larger_size
  - override /generation: regularization
  - override /paths: plgrid
  - override /logger: wandb

data:
  dataloader_num_workers: 4
  max_train_samples: 100
  max_val_samples: 50
  max_test_samples: 50

callbacks:
  model_checkpoint:
    monitor: val/bertscore_f1
    mode: max
    save_top_k: 1
    filename: best-checkpoint

  early_stopping:
    monitor: val/bertscore_f1
    mode: max
    patience: 3