# @package _global_
defaults:
  - override /prompt: llama
  - override /model: caption/llama_3.1_8b_instruct
  - override /trainer: caption_lightning/best
  - override /lora: caption/best
  - override /evaluation: caption/qwen_judge
  - override /generation: caption/best
  - override /paths: plgrid
  - override /logger: wandb

callbacks:
  model_checkpoint:
    monitor: val/bertscore_f1
    mode: max
    save_top_k: 1
    filename: best-checkpoint

  early_stopping:
    monitor: val/bertscore_f1
    mode: max
    patience: 3

logger:
  wandb:
    log_model: false