# @package _global_
defaults:
  - override /prompt: llama
  - override /model: caption/llama_3.1_8b_instruct
  - override /evaluation: caption/qwen_judge
  - override /lora: caption/low_rank
  - override /generation: balanced

data:
  batch_size: 4
  dataloader_num_workers: 16
  max_test_samples: 100
  max_val_samples: 100
  max_train_samples: 100
