# @package _global_
defaults:
  - override /prompt: llama
  - override /model: caption/llama_3.1_8b_instruct
  - override /evaluation: caption/no_judge
  - override /lora: caption/low_rank
  - override /generation: balanced
  - override /paths: plgrid
  - override /logger: wandb

data:
  batch_size: 96
  dataloader_num_workers: 16
  max_test_samples: 500
  max_val_samples: 250
  max_train_samples: 250
