# @package _global_
defaults:
  - override /prompt: llama
  - override /model: caption/llama_3.1_8b_instruct
  - override /trainer: caption_lightning/5_epochs
  - override /lora: caption/regularization
  - override /evaluation: caption/larger_size
  - override /logger: wandb

data:
  batch_size: 32
