# @package _global_
defaults:
  - override /prompt: llama
  - override /model: caption/llama_3.1_8b_instruct
  - override /trainer: caption_lightning/stable
  - override /lora: caption/default
  - override /evaluation: caption/larger_size
  - override /paths: plgrid
  - override /logger: wandb

data:
  max_length: 256
  batch_size: 8
  dataloader_num_workers: 4
  max_train_samples: 100
  max_eval_samples: 50
  max_test_samples: 50

callbacks:
  model_checkpoint:
    monitor: val/bertscore_f1
    mode: max
    save_top_k: 1
    filename: best-checkpoint

  early_stopping:
    monitor: val/bertscore_f1
    mode: max
    patience: 5