# @package _global_
defaults:
  - override /paths: plgrid
  - override /model: caption/llama_3.1_8b_instruct.yaml
  - override /trainer: caption/20_epochs
  - override /lora: caption/regularization
  - override /logger: wandb

data:
  batch_size: 32
