# @package _global_
defaults:
  - override /paths: plgrid
  - override /model: caption/magistral_small_2509_GGUF
  - override /trainer: caption/20_epochs
  - override /lora: caption/regularization
  - override /logger: wandb

data:
  batch_size: 32
