# @package _global_
defaults:
  - override /prompt: mistral
  - override /model: caption/mistral_7b_instruct
  - override /trainer: caption_lightning/15_epochs
  - override /lora: caption/regularization
  - override /evaluation: caption/larger_size
  - override /paths: plgrid
  - override /logger: wandb

data:
  max_length: 256
  batch_size: 8
  dataloader_num_workers: 4
