# @package _global_
defaults:
  - override /paths: plgrid
  - override /prompt: mistral
  - override /model: caption/mistral_7b_instruct
  - override /trainer: caption/5_epochs
  - override /lora: caption/regularization
  - override /evaluation: caption/larger_size
  - override /logger: wandb

data:
  batch_size: 32
