# @package _global_
defaults:
  - override /paths: plgrid
  - override /model: mistral_small_3.1_24B_instruct_2503
  - override /trainer: caption/20_epochs
  - override /lora: caption/regularization
  - override /logger: wandb

data:
  batch_size: 32
