# @package _global_
defaults:
  - override /prompt: mistral
  - override /model: caption/mistral_7b_instruct
  - override /trainer: caption_lightning/stable
  - override /lora: caption/medium_rank
  - override /evaluation: caption/llama_judge
  - override /generation: regularization
  - override /paths: plgrid
  - override /logger: wandb

data:
  batch_size: 16
  dataloader_num_workers: 4
  max_train_samples: 100
  max_val_samples: 100
  max_test_samples: 100

trainer:
  accumulate_grad_batches: 2

callbacks:
  model_checkpoint:
    monitor: val/bertscore_f1
    mode: max
    save_top_k: 1
    filename: best-checkpoint

  early_stopping:
    monitor: val/bertscore_f1
    mode: max
    patience: 3
