# @package _global_
defaults:
  - override /paths: plgrid
  - override /prompt: mistral
  - override /model: caption/mixtral_8x22b_instruct
  - override /trainer: caption/15_epochs
  - override /lora: caption/more_regularization
  - override /evaluation: caption/larger_size
  - override /logger: wandb

data:
  batch_size: 32
