# @package _global_
defaults:
  - override /paths: plgrid
  - override /prompt: mistral
  - override /model: caption/mixtral_8x7b_instruct
  - override /trainer: caption/25_epochs
  - override /lora: caption/more_regularization
  - override /logger: wandb

data:
  batch_size: 32
