# @package _global_
defaults:
  - override /paths: plgrid
  - override /data: caption/load_dataset_mistral
  - override /model: caption/mixtral_8x7b_instruct
  - override /trainer: caption/25_epochs
  - override /lora: caption/regularization
  - override /logger: wandb

data:
  batch_size: 32
