# @package _global_
defaults:
  - override /paths: plgrid
  - override /model: caption/mixtral_8x7b_instruct
  - override /trainer: caption/20_epochs
  - override /lora: caption/regularization
  - override /logger: wandb

data:
  batch_size: 32
