# @package _global_
defaults:
  - override /paths: plgrid
  - override /prompt: qwen
  - override /model: caption/qwen2.5-7b_instruct
  - override /trainer: caption/5_epochs
  - override /lora: caption/regularization
  - override /evaluation: caption/larger_size
  - override /logger: wandb

data:
  batch_size: 32
