clap_model: laion/clap-htsat-unfused
fad_model: laion/clap-htsat-unfused
skip_evaluation: false
text_path: ${paths.data_dir}/metadata.csv
audio_path: ${paths.data_dir}/audio_samples
compute_fad: true
reference_audio_dir: ${paths.data_dir}/reference_audio_samples
