processor_name: "facebook/musicgen-small"
model_name: "facebook/musicgen-small"
model_id: "musicgen"
data_path: "data/music_caps_transformed_instrument.csv"
concept_name: "instrument_guitar"
genre: "rock"
layers: ["model.decoder.lm_heads.0", "model.decoder.lm_heads.1"]
random_state: 42
batch_size: 10
num_samples: 50
experimental_set_size: 5
n_groups: 10
