enabled: true
max_new_tokens: 256
metrics:
  - name: bleu
    kwargs: {}
  - name: rouge
    kwargs: {}
  - name: bertscore
    kwargs:
        lang: en
output_predictions: true
predictions_file: predictions.csv
