enabled: true
max_new_tokens: 256
batch_size: 8
metrics:
  - name: bertscore
    kwargs:
        lang: en
  - name: bleurt
  - name: meteor
  - name: comet
output_predictions: true
predictions_file: predictions.csv
