enabled: true
max_new_tokens: 256
batch_size: 8
metrics:
  - name: bleu
    kwargs: {}
  - name: rouge
    kwargs: {}
  - name: bertscore
    kwargs:
        lang: en
  - name: meteor
    kwargs: {}
  - name: mauve
    kwargs:
      device_id: 1
      featurize_model_name: "gpt2"
output_predictions: true
predictions_file: predictions.csv
