enabled: true
max_new_tokens: 512
batch_size: 32
metrics:
  - name: bleu
    kwargs: {}
  - name: rouge
    kwargs: {}
  - name: bertscore
    kwargs:
        lang: en
  - name: meteor
    kwargs: {}
  - name: google_bleu
    kwargs: {}
output_predictions: true
predictions_file: predictions.csv
