enabled: true
max_new_tokens: 512
batch_size: 8
metrics:
  - name: bleu
    kwargs: {}
  - name: rouge
    kwargs: {}
  - name: bertscore
    kwargs:
        lang: en
  - name: meteor
    kwargs: {}
  - name: perplexity
    kwargs: 
      model_id: "gpt2"
  - name: mauve
    kwargs: {}
output_predictions: true
predictions_file: predictions.csv
