enabled: true
max_new_tokens: 512
batch_size: 32
metrics:
  - name: bertscore
    kwargs:
        lang: en
  - name: cider
  - name: bleurt
  - name: meteor
  - name: comet
output_predictions: true
predictions_file: predictions.csv
