defaults:
  - model: caption/llama_3.1_8b_instruct
  - data: caption/load_dataset
  - prompt: default
  - lora: caption/default
  - trainer: caption/default
  - evaluation: caption/default
  - paths: default
  - logger: null
  - hydra: default

run_id: ${now:%Y-%m-%d_%H-%M-%S}
task_name: caption_evaluation
random_state: 42
device: cuda