defaults:
  - data: caption/load_vae-tags-dataset
  - model: caption/llama_3.1_8b_instruct
  - prompt: default
  - evaluation: caption/default
  - generation: default
  - paths: default
  - logger: null
  - callbacks: default
  - hydra: default

run_id: ${now:%Y-%m-%d_%H-%M-%S}
task_name: caption_inference
device: cuda
random_state: 42

logger:
  wandb:
    project: caption_inference
    log_model: false