defaults:
  - model: caption/mistral_7b_instruct
  - data: caption/create_from_musiccaps
  - lora: caption/default
  - trainer: caption/default
  - evaluation: caption/default
  - paths: default
  - logger: null
  - hydra: default

task_name: caption_dataset
random_state: 42
device: cuda