defaults:
  - model: caption/llama_3.1_8b_instruct
  - data: caption/load_dataset
  - prompt: default
  - lora: caption/default
  - trainer: caption_lightning/default
  - evaluation: caption/default
  - generation: default
  - paths: default
  - logger: null
  - callbacks: default
  - hydra: default

run_id: ${now:%Y-%m-%d_%H-%M-%S}
task_name: caption_fine_tuning
random_state: 42
device: cuda

logger:
  wandb:
    project: caption_fine_tuning
    log_model: true