defaults:
  - model: caption/mistral_7b_instruct
  - data: caption/load_dataset
  - prompt: default
  - lora: caption/default
  - trainer: caption/default
  - evaluation: caption/default
  - paths: default
  - logger: null
  - hydra: default

task_name: caption_evaluation
random_state: 42
device: cuda