defaults:
  - model: caption/mistral_7b_instruct
  - data: caption/musiccaps
  - lora: caption/default
  - training: caption/default
  - evaluation: caption/default
  - paths: default
  - logger: null
  - hydra: default

task_name: caption_generation
seed: 42
device: cuda