defaults:
  - model: musicgen-small
  - data: text_conditioning_guitar_rock
  - experiment: small
  - trainer: default
  - paths: default
  - logger: null
  - hydra: default

device: cuda
random_state: 42
