defaults:
  - model: musicgen-small
  - data: text_conditioning_guitar_rock
  - experiment: layer-feature-ablation-small
  - trainer: default
  - paths: default
  - logger: null
  - hydra: default

task_name: tcav
device: cuda
random_state: 42
