run:
  model:
    processor_name: "facebook/musicgen-small"
    model_name: "facebook/musicgen-small"

  experiment:
    model_id: "musicgen"
    data_path: "data/musicgen"
    concept_name: "intrument_guitar"
    genre: "rock"
    layers: ["layer_1", "layer_2", "layer_3"]

  parameters:
    random_state: 42
    batch_size: 1
    num_samples: 100
    experimental_set_size: 5
    n_groups: 5
