defaults:
  - model: tcav/musicgen-small
  - data: tcav/text_conditioning_guitar_rock
  - experiment: tcav/layer-feature-ablation-small
  - trainer: tcav/default
  - paths: default
  - logger: null
  - hydra: default

task_name: tcav
device: cuda
random_state: 42
