defaults:
  - model: tta/musicgen-small
  - data: tta/musiccaps
  - evaluation: tta/default
  - generation: tta/default
  - paths: default
  - logger: null
  - callbacks: default
  - hydra: default

run_id: ${now:%Y-%m-%d_%H-%M-%S-%f}
task_name: tta_generation
device: cuda
random_state: 42