# @package _global_
defaults:
  - override /paths: plgrid
  - override /model: tta/musicgen-large
  - override /data: tta/final_captions
  - override /generation: musicgen_best
  - override /logger: wandb

data:
  batch_size: 32
  max_sequence_length: 1503
  num_workers: 4
  pin_memory: true
  persistent_workers: true
model:
  compile: true
  device_map: ddp
  tokenizer:
    max_new_tokens: 1503
evaluation:
  skip_evaluation: true

device: cuda