# @package _global_
defaults:
  - override /paths: plgrid
  - override /model: tta/musicgen-large
  - override /data: tta/conceptcaps_test
  - override /generation: tta/best
  - override /logger: wandb

data:
  batch_size: 16
  num_workers: 4
  pin_memory: true
  persistent_workers: true
model:
  compile: true
  device_map: null
  tokenizer:
    max_new_tokens: 750
  use_bf16: false
generation:
  use_accelerator: true
evaluation:
  skip_evaluation: false
  reference_audio_dir: /net/pr2/projects/plgrid/plggailpwln/plgbsienkiewicz/artifacts/data/GTZAN_all

logger:
  wandb:
    project: tta_generation

device: cuda
