# @package _global_
defaults:
  - override /paths: plgrid
  - override /model: tta/musicgen-stereo-large
  - override /data: tta/conceptcaps
  - override /generation: tta/best
  - override /logger: wandb

data:
  batch_size: 3
  num_workers: 2
  pin_memory: true
  persistent_workers: true
model:
  compile: true
  device_map: null
  tokenizer:
    max_new_tokens: 1503
generation:
  use_accelerator: true
evaluation:
  skip_evaluation: true

logger:
  wandb:
    project: tta_generation

device: cuda
