# @package _global_
defaults:
  - override /paths: plgrid
  - override /model: tta/musicgen-large
  - override /data: tta/musicgen-vae-tags-description-dataset
  - override /logger: wandb

data:
  batch_size: 8
  max_sequence_length: 512
model:
  max_new_tokens: 1024
device: cuda