# @package _global_
defaults:
  - override /paths: plgrid
  - override /model: tta/musicgen-large
  - override /data: tta/random_tags
  - override /logger: wandb

data:
  batch_size: 32
  max_sequence_length: 1024
model:
  model:
    max_new_tokens: 1024
device: cuda