max_epochs: 3
accumulate_grad_batches: 4
dataloader_num_workers: 2
accelerator: auto
devices: auto
strategy: ddp
precision: 16-mixed
gradient_clip_val: 0.5
log_every_n_steps: 5
val_check_interval: 0.5
check_val_every_n_epoch: 1
enable_progress_bar: true
enable_model_summary: false
deterministic: false
optimizer:
  lr: 0.000005
  weight_decay: 0.05
  adam_beta1: 0.9
  adam_beta2: 0.999
  eps: 1e-08
lr_scheduler:
  T_max: 3
  eta_min: 0
