_target_: "src.tcav.config.ModelConfig"
model:
  _target_: "src.tcav.model.CustomMusicGen"
  processor:
    _target_: "transformers.AutoProcessor.from_pretrained"
    pretrained_model_name_or_path: "facebook/musicgen-medium"
    device: ${device}
  model:
    _target_: "transformers.MusicgenForConditionalGeneration.from_pretrained"
    pretrained_model_name_or_path: "facebook/musicgen-medium"
model_id: "musicgen-medium"
classifier:
  _target_: "src.tcav.model.SVMClassifier"
