# @package _global_
defaults:
  - override /paths: plgrid
  - override /model: tcav/musicgen-small-with-grad
  - override /experiment: tcav/layer-gradient-x-activation-medium
  - override /trainer: tcav/small
  - override /logger: wandb

data:
  batch_size: 32
